import os;
import re;
import time
from supabase import create_client, Client;
from sentence_transformers import SentenceTransformer;
import spacy
from sklearn.metrics.pairwise import cosine_similarity
import string  
from dotenv import load_dotenv
#REMEMBER: python -m spacy download en_core_web_sm to get the resources for spacy to work
#PLEASE ALSO REMEMBER TO MAKE A .env file
#SQL FOR INSERTING TABLES:
'''
SQL: 
CREATE OR REPLACE FUNCTION create_ctable(table_name TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER 
SET search_path = public 
AS $$
BEGIN
    EXECUTE format('
        CREATE TABLE IF NOT EXISTS %I (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            chunk TEXT,
            embedding REAL[],
            uid TEXT,
            did TEXT
        );
    ', table_name);
    
END;
$$;

THIS MUST BE DEFINED USING THE SQL QUERY INTERFACE ON THE WEBSITE, IF YOU ARE NOT USING THE SECRET/SERVICE KEY, BE SURE TO ADD RLS TO THE FUNCTION
'''

sp = spacy.load("en_core_web_sm")
cmname = "MongoDB/mdbr-leaf-mt"

model = None

def semChunker(doc, window, model, thresh=0.6):
    '''
    First round of chunking to ensure major splits
    doc: string input text 
    window: the sliding semantic window, shrinks as it reaches the end of the doc (int, preferable if even)
    thresh: similarity threshold for window cutoff (value 0-1)
    returns list of chunks [str]
    '''
    window = int(window) if ((int(window) % 2) == 0) else int(window) + 1
    trans = str.maketrans('', '', string.punctuation);
    
    
    ndocs = [];
    lcl = 0;
    for i in range(0, len(doc), 1):
        if lcl > i : continue;
        if len(doc)-i <window:
            if window > 3:
                window = int(window/2)
            else:
                nline = " ".join(doc[lcl:]);
                ndocs.append(nline+" ");
                break;

        larr = doc[i:int(i+(window/2))]
        larr = [l.translate(trans) for l in larr]
        rarr = doc[int(i+(window/2)):int(i+window)]
        rarr = [r.translate(trans) for r in rarr]
        left = model.encode(larr);
        right = model.encode(rarr);  
        similarity_score = cosine_similarity(left, right)[0][0]
    
        if similarity_score <= thresh:
            nline = " ".join(doc[lcl:i+1]);
            ndocs.append(nline);
            lcl = i+1;
    return ndocs;
            
            
def ingestDoc(dstring, modelname="MongoDB/mdbr-leaf-mt", min_size = 50, thresh = 0.6, window = 6):
    '''
    Ingest long string of text, make splits then clean up cmaller chunks semantically
    dstring: string input text (long, doesn't have to be formatted)
    modelname: optionally get any model from huggingface (provided space and specs)
    min_size: int minimum desirable window length
    returns a list of [[chunk, encoding], ...] 
    '''
    global cmname, model
    if modelname == None or modelname == "": modelname = "MongoDB/mdbr-leaf-mt"  #i know i fixed it but just in case
    if modelname != cmname or not model:
        try:
            model = SentenceTransformer(modelname)
            cmname = modelname
        except Exception as e:
            print(f"Error importing model {modelname}: {e}")
        
    trans = str.maketrans('', '', string.punctuation)
    cont_mod = []
    content = sp(dstring)
    content = [s.text for s in content.sents]

    content = semChunker(content, window, model, thresh=thresh)

    
    cw = ""
    for ci in range(0, len(content)):
        if cw != "" and cw[-1] != " " and cw[-1] != ".": cw+=". "
        cw += content[ci]
        if len(cw.split()) < 2:
            cw = ""
            continue
        if len(cw.split()) < min_size and ci>0:
            
            if ci < len(content)-1:
                lenc = model.encode([cont_mod[-1][0].translate(trans)]);
                renc = model.encode([content[ci+1][0].translate(trans)]);
                cenc = model.encode([cw.translate(trans)]);
                lsim = cosine_similarity(lenc, cenc)[0][0]
                rsim = cosine_similarity(renc, cenc)[0][0]
                if lsim>rsim:
                    if cont_mod[-1][0][-1] != "." or cont_mod[-1][0][-2:] != ". ":
                        cont_mod[-1][0] += ". " + cw
                    else:
                        cont_mod[-1][0] += cw
                    cw = ""
            else:
                if cont_mod[-1][0][-1] != "." or cont_mod[-1][0][-2:] != ". ":
                    cont_mod[-1][0] += ". " + cw
                else:
                    cont_mod[-1][0] += cw
                cw = ""
        else:
            cont_mod.append([cw.replace('\n\n', ''), model.encode([cw.translate(trans)])])
            cw = ""
    if cw != "":
        cont_mod[-1][0] += cw.replace('\n\n', '')
        cont_mod[-1][1] = model.encode([cont_mod[-1][0].translate(trans)])
    
    return cont_mod
    
    
load_dotenv()
supaurl = os.getenv('SUPAURL')
supakey = os.getenv('SUPAKEY')
   
def submit_chunks(bname, chunks, docid, uid, curl=supaurl, ckey=supakey):
    '''
    Very simple upload func, MAKE SURE TO HAVE CREATED SQL RPC FUNC ON DASHBOARD AND SET .ENV VARS SUPAURL AND SUPAKEY TO YOUR CREDENTIALS
    bname: name of table (string)
    chunks: [chunk(intact punctuation), embedding(from preprocessed chunk discared after encoding)] list 
    docid: string id for the chunk group/original doc on supabase 
    uid: string id for user
    curl: supabase client url (string, set as env variable and then extract for best practice)
    ckey: supabase client key, same as above except its the key
    '''
    
    supabase: Client = create_client(curl, ckey)
    supabase.rpc('create_ctable', {'table_name': bname}).execute()
    time.sleep(1)
    for c in chunks:
        data = {
            "chunk": c[0],
            "embedding": c[1].tolist(),
            "did": docid,
            "uid": uid
        }
        try:
            
            result = supabase.table(bname).insert(data).execute()
            print(f"Successfully stored chunk with ID: {result.data[0]['id']}")
        except Exception as e:
            print(f"Error storing chunk: {e}")
            
            